### ISSUE TITLE
ddu-source-lspを使えるようにする

### ISSUE THREAD

**Issue by yasunori0418** [yasunori0418/dotfiles#14]

**Comment by yasunori0418** [comment]
やっと本格的にddu-source-lspの設定の為に動ける…はず

**Comment by yasunori0418** [comment]
https://zenn.dev/uga_rosa/articles/8441f13d44300f

**Comment by yasunori0418** [comment]
https://github.com/uga-rosa/dotfiles/blob/main/nvim/lua/rc/helper/ddu.lua#L50-L86

これでいい感じのキーバインドの設定をして、整理したい

**Comment by yasunori0418** [comment]
> https://github.com/uga-rosa/dotfiles/blob/main/nvim/lua/rc/helper/ddu.lua#L50-L86
> 
> これでいい感じのキーバインドの設定をして、整理したい

:munen:
ちょっと相性良くないかも

**Comment by kuuote** [comment]
test :benri:

**Comment by NI57721** [comment]
test :kakko-kabu-tojikakko:

**Comment by yasunori0418** [comment]
みんな遊んでいる:goodpoem:

**Comment by yasunori0418** [comment]
大体設定できたので終了
