### ISSUE TITLE
treesitterのvimdoc強制を受けいれる

### ISSUE THREAD

**Issue by yasunori0418** [yasunori0418/dotfiles#41]
UI的にはリッチになるので、受け入れたいけど、dduのプレビューでエラー地獄になるので回避したい

**Comment by Shougo** [comment]
手元では特にエラーがでた覚えがないので気になりますね。最小構成作れますか？

**Comment by yasunori0418** [comment]
> 手元では特にエラーがでた覚えがないので気になりますね。最小構成作れますか？

これの原因は起動順がみたいなので、もう少し手元で検証してからですかね〜
ちなみにPreviewが開いたときって`BufRead`って発火しないですよね…

**Comment by Shougo** [comment]
あー、自前で読み込んでいた気がします

**Comment by yasunori0418** [comment]
https://github.com/yasunori0418/dotfiles/commit/d702c7d10eb3ee7aa4edb8b22ca58f04a6cde78f

とりあえず、このハックで解決できる。

要約すると、プレビューの中はちゃんとファイルタイプは`help`だけど、treesitterがプラグイン的に読み込まれていないので、ftpluginが発火したときにparserとかを探せなくってエラーになってしまう。
なので、ddu-helpを立ち上げてプレビューする前にtreesitterが読み込まれているのか確認して、読み込まれていなかったら読み込むハックを仕込めば解決できました。

**Comment by Shougo** [comment]
なるほど。遅延起動をしているからですかね。

**Comment by Shougo** [comment]
これやるなら、ddu-helpのon_sourceにnvim-treesitterを追加すればどうですか

**Comment by yasunori0418** [comment]
これで本当に終了
